# -*- coding: utf-8 -*-
"""practical 7 (DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmhEagmwG7WEcAde4oGZydBSv8YrXNLa
"""

# Making Change Problem using Dynamic Programming

def coin_change(coins, amount):
    # dp[i] = minimum number of coins needed to make amount i
    dp = [float('inf')] * (amount + 1)

    # Base case: 0 coins are needed to make amount 0
    dp[0] = 0

    # Build the DP table
    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    # If amount cannot be formed
    if dp[amount] == float('inf'):
        return -1, dp

    return dp[amount], dp


# Input
coins = [1, 2, 5, 10]
amount = 27

# Function call
minimum_coins, dp_table = coin_change(coins, amount)

# Display results
print("Available coins:", coins)
print("Amount:", amount)
print("Minimum number of coins required:", minimum_coins)

print("\nDP Table:")
for i in range(amount + 1):
    print(f"Amount {i}: {dp_table[i]}")