# -*- coding: utf-8 -*-
"""practical 9(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZz5MTbpmjsiidmKJXoVwKPwivpie6se
"""

# Implementation of Prim's Algorithm
# Works directly in Google Colab

import networkx as nx
import matplotlib.pyplot as plt

# Create a weighted undirected graph
G = nx.Graph()

# Add edges: (source, destination, weight)
edges = [
    ('A', 'B', 2),
    ('A', 'C', 3),
    ('B', 'C', 1),
    ('B', 'D', 4),
    ('C', 'D', 5),
    ('C', 'E', 6),
    ('D', 'E', 2)
]

G.add_weighted_edges_from(edges)

# -------------------------------
# Prim's Algorithm
# -------------------------------

def prim_algorithm(graph):
    vertices = list(graph.nodes())

    # Start from the first vertex
    start = vertices[0]

    visited = {start}
    mst_edges = []
    total_weight = 0

    while len(visited) < len(vertices):

        minimum_edge = None
        minimum_weight = float('inf')

        # Find the minimum-weight edge
        # connecting visited to unvisited vertex
        for u in visited:
            for v in graph.neighbors(u):

                if v not in visited:
                    weight = graph[u][v]['weight']

                    if weight < minimum_weight:
                        minimum_weight = weight
                        minimum_edge = (u, v)

        # Add selected edge to MST
        u, v = minimum_edge
        mst_edges.append((u, v, minimum_weight))
        total_weight += minimum_weight
        visited.add(v)

    return mst_edges, total_weight


# Run Prim's Algorithm
mst_edges, total_weight = prim_algorithm(G)

# -------------------------------
# Display MST result
# -------------------------------

print("Edges selected in the Minimum Spanning Tree:")

for u, v, weight in mst_edges:
    print(f"{u} -- {v} : {weight}")

print("\nTotal weight of Minimum Spanning Tree:", total_weight)


# -------------------------------
# Draw Original Graph
# -------------------------------

pos = nx.spring_layout(G, seed=42)

plt.figure(figsize=(8, 6))

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=1500,
    node_color="lightblue",
    font_size=12,
    font_weight="bold"
)

# Display edge weights
edge_labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

plt.title("Original Weighted Graph")
plt.show()


# -------------------------------
# Draw Minimum Spanning Tree
# -------------------------------

MST = nx.Graph()
MST.add_weighted_edges_from(mst_edges)

plt.figure(figsize=(8, 6))

nx.draw(
    MST,
    pos,
    with_labels=True,
    node_size=1500,
    node_color="lightgreen",
    font_size=12,
    font_weight="bold"
)

mst_labels = nx.get_edge_attributes(MST, 'weight')
nx.draw_networkx_edge_labels(MST, pos, edge_labels=mst_labels)

plt.title("Minimum Spanning Tree using Prim's Algorithm")
plt.show()