# -*- coding: utf-8 -*-
"""practical 2(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uwgw1aA2tFlVhntRck0zC2VJlx5pI1Bj
"""

# ==========================================
# LINEAR SEARCH - IMPLEMENTATION & TIME ANALYSIS
# ==========================================

import time

# Input array
arr = [10, 25, 30, 45, 50, 65, 70, 85, 90]

# Element to search
key = 70

print("Array:", arr)
print("Element to search:", key)
print("\n--- Linear Search ---")

# Start time
start_time = time.perf_counter()

# Linear Search
found = False
position = -1

for i in range(len(arr)):
    print(f"Checking element {arr[i]} at index {i}")

    if arr[i] == key:
        found = True
        position = i
        break

# End time
end_time = time.perf_counter()

# Display result
if found:
    print("\nElement found!")
    print("Element:", key)
    print("Index:", position)
    print("Position:", position + 1)
else:
    print("\nElement not found!")

# Time taken
execution_time = end_time - start_time

print("\nExecution Time:", execution_time, "seconds")

# Time complexity
print("\nTime Complexity:")
print("Best Case  : O(1)")
print("Average Case: O(n)")
print("Worst Case : O(n)")

print("\nSpace Complexity: O(1)")

# ==========================================
# BINARY SEARCH - IMPLEMENTATION & TIME ANALYSIS
# ==========================================

import time

# Sorted input array
arr = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# Element to search
key = 70

print("Sorted Array:", arr)
print("Element to search:", key)
print("\n--- Binary Search ---")

# Start time
start_time = time.perf_counter()

# Initialize low and high
low = 0
high = len(arr) - 1

found = False
position = -1

# Binary Search
while low <= high:

    mid = (low + high) // 2

    print(f"Checking middle element {arr[mid]} at index {mid}")

    if arr[mid] == key:
        found = True
        position = mid
        break

    elif arr[mid] < key:
        print("Searching in the right half")
        low = mid + 1

    else:
        print("Searching in the left half")
        high = mid - 1

# End time
end_time = time.perf_counter()

# Display result
if found:
    print("\nElement found!")
    print("Element:", key)
    print("Index:", position)
    print("Position:", position + 1)
else:
    print("\nElement not found!")

# Time taken
execution_time = end_time - start_time

print("\nExecution Time:", execution_time, "seconds")

# Time complexity
print("\nTime Complexity:")
print("Best Case  : O(1)")
print("Average Case: O(log n)")
print("Worst Case : O(log n)")

print("\nSpace Complexity: O(1)")