# -*- coding: utf-8 -*-
"""practical 3(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANwIDcEBy8_E6d7uT2ihV7-Y653hpSth
"""

# Implementation of Max Heap Sort

def heapify(arr, n, i):
    largest = i          # Assume root is largest
    left = 2 * i + 1     # Left child
    right = 2 * i + 2    # Right child

    # Check if left child is greater than root
    if left < n and arr[left] > arr[largest]:
        largest = left

    # Check if right child is greater than current largest
    if right < n and arr[right] > arr[largest]:
        largest = right

    # If largest is not root, swap and continue heapifying
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)


def heap_sort(arr):
    n = len(arr)

    # Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements from heap one by one
    for i in range(n - 1, 0, -1):
        # Move current largest element to the end
        arr[i], arr[0] = arr[0], arr[i]

        # Heapify the reduced heap
        heapify(arr, i, 0)


# Input array
arr = [12, 11, 13, 5, 6, 7]

print("Original Array:", arr)

# Perform Heap Sort
heap_sort(arr)

print("Sorted Array:", arr)