# -*- coding: utf-8 -*-
"""practical 6 (DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeIeqJ8oefi3XrWok8C3Hfm3QFHOstMC
"""

# Chain Matrix Multiplication using Dynamic Programming

def matrix_chain_order(p):
    n = len(p) - 1

    # m[i][j] stores minimum multiplication cost
    m = [[0 for _ in range(n + 1)] for _ in range(n + 1)]

    # s[i][j] stores the position at which the chain is split
    s = [[0 for _ in range(n + 1)] for _ in range(n + 1)]

    # Chain length
    for length in range(2, n + 1):

        for i in range(1, n - length + 2):
            j = i + length - 1

            m[i][j] = float('inf')

            # Try every possible split
            for k in range(i, j):
                cost = (
                    m[i][k]
                    + m[k + 1][j]
                    + p[i - 1] * p[k] * p[j]
                )

                if cost < m[i][j]:
                    m[i][j] = cost
                    s[i][j] = k

    return m, s


# Function to print optimal parenthesization
def print_optimal_parenthesization(s, i, j):

    if i == j:
        return f"A{i}"

    k = s[i][j]

    left = print_optimal_parenthesization(s, i, k)
    right = print_optimal_parenthesization(s, k + 1, j)

    return f"({left} × {right})"


# -----------------------------
# Main Program
# -----------------------------

# Matrix dimensions
# A1 = 10x20
# A2 = 20x30
# A3 = 30x40
# A4 = 40x30

p = [10, 20, 30, 40, 30]

# Calculate minimum cost
m, s = matrix_chain_order(p)

n = len(p) - 1

# Display matrices
print("Matrix Dimensions:")
for i in range(1, n + 1):
    print(f"A{i} = {p[i-1]} x {p[i]}")

# Display minimum cost
print("\nMinimum number of scalar multiplications:")
print(m[1][n])

# Display optimal parenthesization
print("\nOptimal Parenthesization:")
print(print_optimal_parenthesization(s, 1, n))

# Display DP table
print("\nDynamic Programming Cost Table:")

for i in range(1, n + 1):
    for j in range(1, n + 1):
        if i <= j:
            print(f"m[{i}][{j}] = {m[i][j]}")
    print()