# -*- coding: utf-8 -*-
"""practical 8(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102Q63gdpcd-hhLMIcU33Typr8MTQNsB5
"""

# Graph Implementation using Adjacency List

class Graph:
    def __init__(self):
        self.graph = {}

    # Add an edge between two vertices
    def add_edge(self, vertex1, vertex2):
        if vertex1 not in self.graph:
            self.graph[vertex1] = []

        if vertex2 not in self.graph:
            self.graph[vertex2] = []

        self.graph[vertex1].append(vertex2)
        self.graph[vertex2].append(vertex1)

    # Display the graph
    def display(self):
        for vertex in self.graph:
            print(vertex, "->", self.graph[vertex])


# Create graph
g = Graph()

# Add edges
g.add_edge("A", "B")
g.add_edge("A", "C")
g.add_edge("B", "D")
g.add_edge("B", "E")
g.add_edge("C", "F")
g.add_edge("E", "F")

# Display graph
print("Graph:")
g.display()

# BFS - Breadth First Search

from collections import deque

class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, vertex1, vertex2):
        if vertex1 not in self.graph:
            self.graph[vertex1] = []

        if vertex2 not in self.graph:
            self.graph[vertex2] = []

        self.graph[vertex1].append(vertex2)
        self.graph[vertex2].append(vertex1)

    def bfs(self, start):
        visited = set()
        queue = deque()

        # Start from the given vertex
        queue.append(start)
        visited.add(start)

        print("BFS Traversal:")

        while queue:
            vertex = queue.popleft()
            print(vertex, end=" ")

            # Visit all adjacent vertices
            for neighbor in self.graph[vertex]:
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append(neighbor)


# Create graph
g = Graph()

g.add_edge("A", "B")
g.add_edge("A", "C")
g.add_edge("B", "D")
g.add_edge("B", "E")
g.add_edge("C", "F")
g.add_edge("E", "F")

# Perform BFS starting from A
g.bfs("A")

# DFS - Depth First Search

class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, vertex1, vertex2):
        if vertex1 not in self.graph:
            self.graph[vertex1] = []

        if vertex2 not in self.graph:
            self.graph[vertex2] = []

        self.graph[vertex1].append(vertex2)
        self.graph[vertex2].append(vertex1)

    def dfs(self, start):
        visited = set()

        print("DFS Traversal:")

        self.dfs_recursive(start, visited)

    def dfs_recursive(self, vertex, visited):
        # Mark vertex as visited
        visited.add(vertex)

        print(vertex, end=" ")

        # Visit adjacent vertices
        for neighbor in self.graph[vertex]:
            if neighbor not in visited:
                self.dfs_recursive(neighbor, visited)


# Create graph
g = Graph()

g.add_edge("A", "B")
g.add_edge("A", "C")
g.add_edge("B", "D")
g.add_edge("B", "E")
g.add_edge("C", "F")
g.add_edge("E", "F")

# Perform DFS starting from A
g.dfs("A")

# Graph Implementation and Visualization

import networkx as nx
import matplotlib.pyplot as plt

# Create an undirected graph
G = nx.Graph()

# Add edges
G.add_edges_from([
    ("A", "B"),
    ("A", "C"),
    ("B", "D"),
    ("B", "E"),
    ("C", "F"),
    ("E", "F")
])

# Display graph
plt.figure(figsize=(8, 6))

pos = {
    "A": (0, 2),
    "B": (-2, 1),
    "C": (2, 1),
    "D": (-3, 0),
    "E": (-1, 0),
    "F": (2, 0)
}

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=15,
    font_weight="bold"
)

plt.title("Graph Representation")
plt.show()

# BFS (Breadth First Search) with Graph Visualization

import networkx as nx
import matplotlib.pyplot as plt
from collections import deque

# Create graph
G = nx.Graph()

# Add edges
G.add_edges_from([
    ("A", "B"),
    ("A", "C"),
    ("B", "D"),
    ("B", "E"),
    ("C", "F"),
    ("E", "F")
])

# BFS function
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)

    traversal = []

    while queue:
        vertex = queue.popleft()
        traversal.append(vertex)

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

    return traversal


# Perform BFS starting from A
start_node = "A"
bfs_result = bfs(G, start_node)

# Print traversal
print("BFS Traversal:")
print(" -> ".join(bfs_result))


# Draw graph
plt.figure(figsize=(8, 6))

pos = {
    "A": (0, 2),
    "B": (-2, 1),
    "C": (2, 1),
    "D": (-3, 0),
    "E": (-1, 0),
    "F": (2, 0)
}

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=15,
    font_weight="bold"
)

plt.title("Graph - BFS Traversal")
plt.show()

# DFS (Depth First Search) with Graph Visualization

import networkx as nx
import matplotlib.pyplot as plt

# Create graph
G = nx.Graph()

# Add edges
G.add_edges_from([
    ("A", "B"),
    ("A", "C"),
    ("B", "D"),
    ("B", "E"),
    ("C", "F"),
    ("E", "F")
])


# DFS function
def dfs(graph, vertex, visited, traversal):

    visited.add(vertex)
    traversal.append(vertex)

    for neighbor in graph[vertex]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited, traversal)


# Perform DFS
start_node = "A"

visited = set()
dfs_result = []

dfs(G, start_node, visited, dfs_result)


# Print traversal
print("DFS Traversal:")
print(" -> ".join(dfs_result))


# Draw graph
plt.figure(figsize=(8, 6))

pos = {
    "A": (0, 2),
    "B": (-2, 1),
    "C": (2, 1),
    "D": (-3, 0),
    "E": (-1, 0),
    "F": (2, 0)
}

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=15,
    font_weight="bold"
)

plt.title("Graph - DFS Traversal")
plt.show()