# -*- coding: utf-8 -*-
"""practical 4(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soaCKIFJWevi7dyRuVsxIZ_zAt91AmGk
"""

# Factorial using Iterative Method

def factorial_iterative(n):
    fact = 1

    for i in range(1, n + 1):
        fact = fact * i

    return fact


# Taking input from the user
n = int(input("Enter a non-negative integer: "))

if n < 0:
    print("Factorial is not defined for negative numbers.")
else:
    result = factorial_iterative(n)
    print("Factorial of", n, "using Iterative Method =", result)\